blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/alessandroamella/codice-fiscale-ts/discussions
    about: Please discuss non bug-related topics there
