name: codice-fiscale-ts

on:
  push:
    branches:
      - main
      - master
      - next
      - beta
      - alpha
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  NODE_AUTH_TOKEN:

jobs:
  lint:
    name: ðŸ”¬ Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: true
      - name: ðŸ”¬ Lint
        run: pnpm run lint

  type-check:
    name: Ê¦ Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: true
      - name: Ê¦ Typecheck
        run: pnpm run type:check

  test:
    name: âš¡ Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: true
      - name: âš¡ Tests
        run: pnpm run test:coverage

  build-and-release:
    name: ðŸš€ Build & release
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/next' || github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/alpha')
    needs: [lint, type-check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: true
      - name: ðŸ”¨ Build
        run: pnpm run build
      - name: ðŸš€ Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run semantic-release
